# Generated by Django 5.0.6 on 2024-06-22 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("tagline", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField()),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("website_url", models.URLField()),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("approval_required", models.BooleanField(default=False)),
                (
                    "application_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("membership_available", models.BooleanField(default=False)),
                (
                    "mailing_street",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mailing_street2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mailing_city",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "mailing_state",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                ("mailing_zip", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "physical_street",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "physical_street2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "physical_city",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "physical_state",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "physical_zip",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("event_url", models.URLField(blank=True, null=True)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("address2", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=2)),
                ("zip", models.CharField(blank=True, max_length=10, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("membership_required", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.host",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tier", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("benefits", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("duration", models.IntegerField(blank=True, null=True)),
                (
                    "duration_type",
                    models.CharField(
                        choices=[
                            ("D", "days"),
                            ("W", "weeks"),
                            ("M", "months"),
                            ("Y", "years"),
                            ("L", "lifetime"),
                        ],
                        max_length=1,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="api.host",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("SM", "Single Gentleman"),
                            ("SF", "Single Lady"),
                            ("C", "Couple"),
                        ],
                        max_length=2,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("conditions", models.TextField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="api.event",
                    ),
                ),
            ],
        ),
    ]
