# Generated by Django 5.0.6 on 2024-06-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
