# Generated by Django 5.0.6 on 2024-07-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="requires_approval_for_view",
            field=models.BooleanField(default=False),
        ),
    ]
