# Generated by Django 5.0.6 on 2024-07-09 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_hostapplication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("dob", models.DateField()),
                (
                    "age_display",
                    models.CharField(
                        choices=[
                            ("NUMBER", "Number"),
                            ("GENERATION", "Generation"),
                            ("RANGE", "Range"),
                            ("NONE", "None"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("CIS_M", "CIS M"),
                            ("CIS_F", "CIS F"),
                            ("TRANS_M", "Trans M"),
                            ("TRANS_F", "Trans F"),
                            ("NON_BINARY", "Non-Binary"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sexuality",
                    models.CharField(
                        choices=[
                            ("STRAIGHT", "Straight"),
                            ("HETERO", "Heteroflexible"),
                            ("BI_CURIOUS", "Bi-curious"),
                            ("BISEXUAL", "Bisexual"),
                            ("HOMO", "Homoflexible"),
                            ("GAY", "Gay/Lesbian"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("about_you", models.TextField(blank=True, null=True)),
                ("relationship_status", models.TextField(blank=True, null=True)),
                ("personal_background", models.TextField(blank=True, null=True)),
                ("experience", models.TextField(blank=True, null=True)),
                ("community_contribution", models.TextField(blank=True, null=True)),
                ("philosophy_views", models.TextField(blank=True, null=True)),
                ("fantasy_preferences", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
