# Generated by Django 5.0.6 on 2024-07-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("CIS_M", "CIS M"),
                    ("CIS_F", "CIS F"),
                    ("TRANS_M", "Trans M"),
                    ("TRANS_F", "Trans F"),
                    ("NON_BINARY", "Non-Binary"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="sexuality",
            field=models.CharField(
                choices=[
                    ("STRAIGHT", "Straight"),
                    ("HETERO", "Heteroflexible"),
                    ("BI_CURIOUS", "Bi-curious"),
                    ("BISEXUAL", "Bisexual"),
                    ("HOMO", "Homoflexible"),
                    ("GAY", "Gay/Lesbian"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
