# Generated by Django 5.0.6 on 2024-08-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_userresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
