# Generated by Django 5.0.6 on 2024-08-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_userresponse_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="quiz_type",
            field=models.CharField(
                choices=[("Standard", "Standard"), ("Extended", "Extended")],
                default="Standard",
                max_length=10,
            ),
        ),
    ]
