# Generated by Django 5.0.6 on 2024-08-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_quizquestion_quiz_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestion",
            name="quiz_type",
            field=models.CharField(
                choices=[
                    ("Standard", "Standard"),
                    ("Extended", "Extended"),
                    ("Archived", "Archived"),
                ],
                default="Standard",
                max_length=10,
            ),
        ),
    ]
