# Generated by Django 5.0.6 on 2024-12-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
