app = "rv-backend"

[env]
PORT = "8000"

[[services]]
http_checks = []
internal_port = 8000
protocol = "tcp"
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

[[services.ports]]
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[mounts]
source="rv_backend_volume1"
destination="/data"